using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Briefcase.Domain.Entities;
using Briefcase.Infrastructure.Persistence;

namespace Briefcase.ApiService.Controllers;

/// <summary>
/// Serves one-time share links generated by the transfer flow.
/// No authentication required — the slug is the access credential.
/// </summary>
[ApiController]
[Route("api/share")]
public class ShareController(AppDbContext db) : ControllerBase
{
    // GET /api/share/{slug}  →  retrieve shared message content (marks one-time links as used)
    [HttpGet("{slug}")]
    public async Task<IActionResult> GetSharedMessage(string slug)
    {
        if (string.IsNullOrWhiteSpace(slug) || slug.Length > 64)
            return BadRequest();

        var shareLink = await db.ShareLinks
            .Include(s => s.Message)
                .ThenInclude(m => m.FileAttachment)
            .FirstOrDefaultAsync(s => s.Slug == slug);

        if (shareLink is null || shareLink.RevokedAt.HasValue)
            return NotFound();

        if (shareLink.ExpiresAt.HasValue && shareLink.ExpiresAt < DateTime.UtcNow)
            return NotFound();

        var message = shareLink.Message;
        if (message.IsDeleted)
            return NotFound();

        // Revoke immediately if this is a one-time link
        if (shareLink.IsOneTime)
            shareLink.RevokedAt = DateTime.UtcNow;

        shareLink.ViewCount++;
        await db.SaveChangesAsync();

        return Ok(new SharedMessageDto(
            message.Id,
            message.Kind.ToString(),
            message.Content,
            message.FileId,
            message.FileAttachment?.OriginalName,
            message.FileAttachment?.PreviewBlobPath is not null
                ? $"/api/files/{message.FileAttachment.Id}/preview"
                : null,
            message.CreatedAt));
    }
}

public record SharedMessageDto(
    Guid MessageId,
    string Kind,
    string? Content,
    Guid? FileId,
    string? FileName,
    string? FilePreviewUrl,
    DateTime CreatedAt);
